config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :cars do
    resources :deals, only: %i[new create]
    resources :reviews, only: %i[create]
  end

  resources :deals, only: %i[index show edit update] do
    get "my", on: :collection
  end

  resources :reviews, only: %i[index show edit update] do
    get "my", on: :collection
  end

  resource :profiles, only: :show
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :deals
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

  validates :brand, :model, :km, presence: true

  include PgSearch::Model
  pg_search_scope :search_cars,
    against: [ :model, :brand ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :car
  belongs_to :user

  def seller
    car.user
  end

  def buyer
    user
  end

  def self.by_seller(user)
    Deal.joins(car: :user).where(car: {user: user})
  end

  validates :price, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :post, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :deals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cars, dependent: :destroy
  has_many :cars, through: :deals
  has_one :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show delete edit update]
  def index
    @cars = Car.all
    if params[:query].present?
      @cars = Car.search_cars(params[:query])
    end
  end

  def show
    @review = Review.new()
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to profiles_path
  end

  def delete
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model, :year, :km, :photo, :initial_price)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    @review = Review.new()
    @seller_deals = Deal.by_seller(current_user)
  end

  def my
    @buyer_deals = current_user.deals
  end

  def new
    @car = Car.find(params[:car_id])
    @deal = Deal.new()
    @buyer = current_user
    # raise
  end

  def create
    @buyer = current_user
    @car = Car.find(params[:car_id])
    @deal = Deal.new(deal_params)
    @deal.user = @buyer
    @deal.car = @car
    @deal.save
    redirect_to deals_path(@deal)
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    @deal.update(accepted?: true)

    redirect_to deals_path
  end

  private

  def deal_params
    params.require(:deal).permit(:price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @sorted_cars = Car.order("RANDOM()").limit(9)

    return unless params[:query].present?

    @sorted_cars = Car.search_cars(params[:query])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @cars = Car.where(user_id: @user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @user = current_user
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    @review.user = @user
    if @review.save
      redirect_to car_path(@review.car)
    else
      render "cars/show", car: @car, review: @review, status: :unprocessable_entity
    end
  end

  private


  def review_params
    params.require(:review).permit(:post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for car do |f| %>
  <%= f.input :brand, placeholder: "Fabricante ou marca do carro" %>
  <%= f.input :model, placeholder: "Modelo do Carro" %>
  <%= f.input :year, placeholder: "Ano de Fabricação" %>
  <%= f.input :km, placeholder: "Km's Rodados" %>
  <%= f.input :initial_price, placeholder: "Por quanto quer vender" %>
  <%= f.input :photo, as: :file, placeholder: "Uma foto de destaque do carro" %>
  <%= f.submit %>
<% end %>
<hr>

app/views/cars/index.html.erb
<h1 class="hd-car-dark text-center">Todas as ofertas</h1>
<div class="container">
  <br>
  <br>
  <br>
    <%= form_with url: cars_path, method: :get, class: "d-flex mb-3 src" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Ache o carro ideal para você"
        %>
      <%= submit_tag "Buscar", name: "", class: "btn btn-flat" %>
    <% end %>
  <% @cars.each do |car| %>
    <div class="card card-bls mb-5" style="max-width: 1200px;">
      <div class="row row-hz g-0">
        <div class="col-md-4">
          <% if car.photo.attached? %>
            <%= cl_image_tag car.photo.key, crop: :fill, class: "img-fit" %>
          <% else %>
            <%= image_tag "car_placeholder.jpg" %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body h-100">
            <h4 class="card-title">Modelo: <strong-r> <%= car.model %></strong-r>,</h4>
            <h4 class="card-title mb-3"> Fabricante: <strong-r> <%= car.brand %> </strong-r></h4>
            <p class="card-text"><small class="text-muted">Ano: <%= car.year %></small></p>
            <p class="card-text"><small class="text-muted">Kilometragem: <%= car.km %></small></p>
            <h5 class="card-text mb-1"><small class="text-muted"><strong-r><%= car.initial_price %>,00$ </strong-r></small></h5>
            <%= link_to "Mais Detalhes", car_path(car), class: "btn btn-flat" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<div class="container">

  <h1>Liste seu carro na plataforma</h1>
  <br>
  <%= render "form", car: @car %>
  <br>
  <div class="container mb-3">
    <%= link_to "Volte para a pesquisa de todos os carros", cars_path, class: "btn btn-dark" %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container p-3">
  <div class="d-flex justify-content-center">
    <% if @car.photo.attached? %>
      <%= cl_image_tag @car.photo.key, crop: :fill, class: "img-show mt-2" %>
    <% else %>
      <%= image_tag "car_placeholder.jpg" %>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-8">
      <div class="card card-bls">
        <div class="card-body">
          <h3 class="card-title text-center"><strong><%= @car.model %></strong>, <strong-r><%= @car.brand %></strong-r></h3>
          <hr>
          <p class="card-text">Vendedor: <%= @car.user.first_name %> <%= @car.user.last_name %></p>
          <p class="card-text">Kilometragem: <%= @car.km %></p>
          <p class="card-text">Ano: <%= @car.year %></p>
        </div>
        <div class="card card-body mt-5">
          <%= render "reviews/form", review: @review, car: @car %>
        </div>
      </div>
    </div>
    <div class="col-4 text-center">
      <div class="card-body p-4">
        <h3 class="card-title">Oferta</h3>
        <h5 class="card-text">Preço pedido: <%= @car.initial_price %>,00$</h5>
        <div class="card-footer text-center">
          <%= link_to "Dê uma oferta neste carro", new_car_deal_path(@car), class: "btn btn-gradient" %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container mb-5">
  <% @car.reviews.where.not(user: [@car.deals.map(&:user), @car.user]).each do |r|%>
   <div class="card-body">
    <h3> <%= r.user.first_name %> <%= r.user.last_name %>, perguntou </h3>
      <%= r.post %>
      <hr>
   </div>
  <% end %>
</div>
<div class="px-5 pb-5">
  <%= link_to "Voltar", cars_path, class: "btn btn-dark" %>
</div>

app/views/deals/_buyer_form.html.erb
<%= simple_form_for [@car, @deal] do |f| %>
  <h5 class="card-title text-center"><strong>Oferta</strong> <%= f.input :price, placeholder: "Quanto quer ofertar?" %> </h5>
  <p class="card-text"></p>

  <%= f.submit "Enviar oferta" %>
<% end %>
<hr>

app/views/deals/_edit_form.html.erb
<%= simple_form_for deal do |f| %>
  <%= f.submit "Aceitar oferta" %>
<% end %>

app/views/deals/index.html.erb
<h1 class="hd-car-dark text-center"> Todas as suas ofertas para avaliação</h1>
<div class="container m-top">
  <% @seller_deals.each do |s| %>
    <div class="card card-bls mb-3" style="max-width: 1200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <% if s.car.photo.attached? %>
            <%= cl_image_tag s.car.photo.key, crop: :fill, class: "img-fit" %>
          <% else %>
            <%= image_tag "car_placeholder.jpg", class: "img-fit" %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body p-fit">
            <div>
              <h3 class="card-title">Oferta: <strong-r><%= s.price %>,00$</strong-r></h3>
              <h5 class="card-text">Preço inicial <%= s.car.initial_price %>,00$</h5>
              <% if s.accepted? %>
                <p class="card-text bg-success text-white"> Voce já aceitou essa oferta de <%= s.buyer.first_name %></p>
              <% else %>
                <%= render "edit_form", deal: s %>
                <%= render "reviews/form", review: @review, car: s.car %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container mb-5">
      <% s.car.reviews.where(user: [s.user, s.car.user]).each do |r|%>
        <div class="card-body">
          <h3> <%= r.user.first_name %> <%= r.user.last_name %>, perguntou </h3>
            <%= r.post %>
            <hr>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/deals/my.html.erb
<h1 class="hd-car-dark text-center"> Todas as suas ofertas criadas</h1>
<div class="container m-top">
  <% @buyer_deals.each do |b| %>
    <div class="card card-bls mb-3" style="max-width: 1200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <% if b.car.photo.attached? %>
            <%= cl_image_tag b.car.photo.key, crop: :fill, class: "img-fit" %>
          <% else %>
            <%= image_tag "car_placeholder.jpg", class: "img-fit" %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body p-fit">
            <h3 class="card-title">
              <% if b.accepted? %>
                <%= b.seller.first_name %> Aceitou sua proposta! Parabéns!
              <% else %>
                <p> Sua oferta ainda não foi aceita, </p>
                <p> espere por <%= b.seller.first_name %> </p>
              <% end %>
            </h3>
            <%= link_to "Detalhes", deal_path(b), class: "btn btn-dark mt-4" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/deals/new.html.erb
<h1 class="bg-dark bg-gradient text-white text-center p-2"> Confirmação de preço para <%= @car.brand %> <%= @car.model %>, <%= @car.year %></h1>
<div class="container mt-2">
  <h3> Converse com <%= @car.user.first_name %>, para chegarem a um acordo</h3>
</div>
<hr>
<div class="container m-3">
  <div class="card">
    <div class="card-header text-center">
      <%= @buyer.first_name %> <%= @buyer.last_name %>
    </div>
    <div class="card-body">
      <%= render "buyer_form", deal: @deal %>
    </div>
  </div>
  <%= link_to "Voltar", car_path(@car), class: "btn btn-dark mt-3" %>
</div>

app/views/deals/show.html.erb
<div class="hd-car-dark text-center">
<% dealing_car = @deal.car %>
  <h1>Minha oferta para <%= dealing_car.model %></h1>
</div>
<div class="card mt-5">
  <% if @deal.car.photo.attached? %>
    <%= cl_image_tag dealing_car.photo.key, crop: :fill, class: "img-show mb-4" %>
  <% else %>
    <%= image_tag "car_placeholder.jpg", class: "img-show mb-4"%>
  <% end %>
  <div class="card-body mb-4">
    <div class="card-footer text-center">
      <% if @deal.accepted? %>
        <%= @deal.seller.first_name %> Aceitou sua proposta! Parabéns!
        Entre em contato por <%= @deal.seller.email %>
        <% else %>
        Sua oferta ainda não foi aceita, espere por <%= @deal.seller.first_name %>
      <% end %>
    </div>
    <%= link_to "Voltar", my_deals_path, class: "btn btn-dark" %>
  </div>
</div>

  <div class="container mb-5">
    <% @deal.car.reviews.where(user: [@deal.user, @deal.car.user]).each do |r|%>
      <div class="card-body">
        <h3> <%= r.user.first_name %> <%= r.user.last_name %>, perguntou </h3>
          <%= r.post %>
          <hr>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tr3s Roda 🚘</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Sinta-se em casa aqui na <strong>Tr3s Roda</strong>!</h1>
    <p>Onde você é quem faz tudo rodar</p>
    <%= link_to "Agora só falta você!", new_user_registration_path, class: "btn btn-flat" %>
  </div>
</div>
<hr>
    <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: root_path, method: :get, class: "d-flex src" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Ache o carro ideal para você"
        %>
      <%= submit_tag "Buscar", name: "", class: "btn btn-flat" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="d-flex justify-content-between">
    <h3 class="mt-3">Veja as principais ofertas!</h3>
    <a class="btn btn-index m-3" href="/cars">Veja todas as ofertas!</a>
  </div>
  <ul class="list-group list-group-horizontal list-group-flush justify-content-evenly row">
        <% @sorted_cars.each do |c| %>
          <li class="list-group-item mb-4 col-4">
            <div class="card">
              <% if c.photo.attached? %>
                <%= cl_image_tag c.photo.key, height: 300, width: 400, crop: :fill, class: "card-banner card-img-top" %>
              <% else %>
                <%= image_tag "car_placeholder.jpg" %>
              <% end %>
              <div class="card-hd text-center">
                Modelo: <%=c.model%> // Ano: <%= c.year %>
              </div>
              <div class="card-body">
                <h5 class="card-title">Fabricante: <strong-r><%= c.brand %></strong-r></h5>
                <p class="card-text">Km rodados: <%= c.km %></p>
                <%= link_to "Veja mais informações", car_path(c), class: "btn btn-flat" %>
              </div>
            </div>
          </li>
          <br>
        <% end %>
      </div>
  </ul>
    <a class="btn btn-index m-3" href="/cars">Veja todas as ofertas!</a>
</div>

app/views/profiles/_car_edit_form.html.erb
<%= simple_form_for car do |f| %>
  <%= f.input :initial_price, car_placeholder: "novo preço" %>
  <%= f.input :km, car_placeholder: "Km rodados" %>
  <%= f.input :photo, car_placeholder: "Nova foto" %>
  <%= f.submit "Atualizar" %>
<% end %>

app/views/profiles/_config.erb
  <div class="container">
    <h2 class="card-title">Olá, <%= @user.first_name %>!</h2>
    <br>
    <p class="card-text">Email atual: <%= @user.email %>
    <%= link_to "Edite seu email", "#", class: "btn btn-secondary" %></p>
    <p>Nome completo : <%= @user.first_name %> <%= @user.last_name %>
    <%= link_to "Mude seu nome", "#", class: "btn btn-secondary" %></p>
    <p><%= link_to "Atualize sua senha", "#", class: "btn btn-secondary" %></p>
  </div>

app/views/profiles/_my_cars.html.erb
<% @user.cars.each do |car| %>
    <div class="card mb-3" style="max-width: 1200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <% if car.photo.attached? %>
            <%= cl_image_tag car.photo.key, crop: :fill, class: "card-banner card-img-top" %>
          <% else %>
            <%= image_tag "car_placeholder.jpg" %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h3 class="card-title">Modelo: <%= car.model %>, Fabricante: <%= car.brand %></h3>
            <p class="card-text"><small class="text-muted">Ano: <%= car.year %></small></p>
            <p class="card-text"><small class="text-muted">Kilometragem: <%= car.km %></small></p>
            <h5 class="card-text">Preço pedido: <%= car.initial_price %>$</h5>
          </div>
        </div>
      </div>
      <%= link_to "Mais Detalhes", car_path(car), class: "btn btn-flat" %>
    </div>
<% end %>

app/views/profiles/show.html.erb
<nav>
  <div class="nav nav-tabs mt-5" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-cars-tab" data-bs-toggle="tab" data-bs-target="#nav-cars" type="button" role="tab" aria-controls="nav-cars" aria-selected="true">Meus Carros</button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Configurações</button>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
    <%# tab de meus carros %>
  <div class="tab-pane fade show active" id="nav-cars" role="tabpanel" aria-labelledby="nav-cars-tab">
    <div class="container m-5 ">
      <div class="card card-bls">
        <% @cars.each do |car| %>
          <div class="card card-bls mb-3" style="max-width: 1200px;">
            <div class="row g-0">
              <div class="col-md-4">
                <% if car.photo.attached? %>
                  <%= cl_image_tag car.photo.key, crop: :fill, class: "card-banner img-fluid" %>
                <% else %>
                  <%= image_tag "car_placeholder.jpg" %>
                <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body" data-controller="form">
                  <h3 class="card-title mb-3">Modelo: <strong-r><%= car.model %></strong-r>, Fabricante: <strong-r><%= car.brand %></strong-r></h3>
                  <p class="card-text"><small class="text-muted">Ano: <%= car.year %></small></p>
                  <p class="card-text mb-3"><small class="text-muted">Kilometragem: <%= car.km %></small></p>
                  <h5 class="card-text"><strong-r>Preço pedido: </strong-r> <%= car.initial_price %>,00$</h5>
                  <%# <%= link_to "Editar",  edit_car_path(car), class: "btn btn-ghost" %>
                  <button type="button" class="btn btn-ghost-fill" data-action="click->form#toggle">
                    Editar
                  </button>
                  <div class="card card-bls mt-4 d-none form-bg" data-form-target="carForm">
                    <%= render "car_edit_form", car: car %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
    <%# tab de configs %>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
    <div class="container m-5">
      <div class="container mb-4">
        <h2 class="card-title">Olá, <%= @user.first_name %>!</h2>
        <br>
        <div class="container mb-4">
          <p class="card-text">Email atual: <%= @user.email %></p>
          <%= link_to "Edite seu email", "#", class: "btn btn-secondary" %>
        </div>
        <div class="container mb-4">
          <p>Nome completo : <%= @user.first_name %> <%= @user.last_name %></p>
          <%= link_to "Mude seu nome", "#", class: "btn btn-secondary" %>
        </div>
        <p><%= link_to "Atualize sua senha", "#", class: "btn btn-secondary" %></p>
      </div>
    </div>
  </div>
</div>
  <div class="container">
    <%= link_to "Voltar", cars_path, class: "btn btn-dark" %>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [car, review] do |f| %>
  <%= f.input :post, placeholder: "Escreva sua mensagem aqui" %>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="flash flash-success alert alert-dismissible fade show" role="alert">
      <span><strong>Parabéns!</strong> 🎉 Tudo pronto para rodar.</span>
      <a data-bs-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
    </div>
<% end %>

<% if alert %>
    <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
      <span><strong>Oops!</strong> ⚠️ parece que alguma coisa deu errado!</span>
      <a data-bs-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Minhas ofertas", "/deals/my", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Interessados", "/deals", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Coloque seu carro aqui", new_car_path, class: "dropdown-item" %>
              <%= link_to "Meu perfil", profiles_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>